name: Compile MCA

on:
  workflow_dispatch:
    inputs:
      make_args:
        description: pass extra make argumments to control features not explicitly handled by CI
  push:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.0
    steps:

    - name: Install dependencies
      run: |
        apk add make git zip

    - uses: actions/checkout@v4
    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow

    - name: Compile
      run: |
        make clean all packlang -C MCA EE_BIN_DIR=../mca_legacy
        make clean all packlang -C MCA EE_BIN_DIR=../mca_exfat EXFAT=1
        make clean all packlang -C MCA EE_BIN_DIR=../mca_Arcade EXFAT=1 MGMODE=ARCADE
        make clean all packlang -C MCA EE_BIN_DIR=../mca_Prototype EXFAT=1 MGMODE=PROTOTYPE
        make clean all packlang -C MCA EE_BIN_DIR=../mca_Developer EXFAT=1 MGMODE=DEVELOPER

    - name: Pack
      run: |
        zip -r MemoryCardAnihilator.zip ./mca_legacy/* ./mca_exfat/* ./mca_Arcade/* ./mca_Prototype/* ./mca_Developer/* README.MD

    - name: Upload variants artifact ELF
      uses: actions/upload-artifact@v4
      with:
        name: "MCA"
        path: |
            MemoryCardAnihilator.zip

    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest automated build"
        prerelease: false
        files: |
               MemoryCardAnihilator.zip
